// <auto-generated />
using System;
using Data_Access.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Access.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20201220181458_l")]
    partial class l
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Data_Access.GameInstraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("GameImageURL")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("GameName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("GameURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameInstractions");
                });

            modelBuilder.Entity("Data_Access.Grand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Grand");
                });

            modelBuilder.Entity("Data_Access.JackbotWinner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfWinning")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GotIt")
                        .HasColumnType("bit");

                    b.Property<string>("JackbotName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("WinnerName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.ToTable("jackbotWinner");
                });

            modelBuilder.Entity("Data_Access.Models.ChargeHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("BalanceIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ChargeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("Creater");

                    b.ToTable("ChargeHistories");
                });

            modelBuilder.Entity("Data_Access.Models.GameHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FreeSpin")
                        .HasColumnType("bit");

                    b.Property<string>("GameName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lines")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("WLAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Wild")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("Creater");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("Data_Access.Models.LoginHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Creater")
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("Creater");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("Data_Access.Models.Major", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("Data_Access.Models.Mini", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Mini");
                });

            modelBuilder.Entity("Data_Access.Models.Minor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Creater")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Mainer");
                });

            modelBuilder.Entity("Data_Access.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Creater")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DoubleBunosActive")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<double>("Level")
                        .HasColumnType("float");

                    b.Property<int>("LoginTimes")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercantageOfLuck")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Username");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Username = "Christina Strosin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Frederick Kautzer",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Terrance Wunsch",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Tabitha Boyle",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Marta Hoppe",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Nathaniel Rutherford",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Stuart Carter",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kristy Koelpin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Ramiro Haag",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Beulah Cummings",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Opal Schmitt",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Tony Bogisich",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Johnnie Leffler",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Sergio Bailey",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Paulette Windler",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Christopher Walsh",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Sabrina Mayer",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Ana Lindgren",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Israel Conroy",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Rhonda Bechtelar",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kelli Weissnat",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lorene Koepp",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Mercedes Nolan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Randy MacGyver",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Camille Ernser",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Hubert Kilback",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lucas Swaniawski",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kari Dickens",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Dixie Wyman",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Janis Shanahan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Bradley Schroeder",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Gilberto Schowalter",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jermaine Gerlach",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Sherri Hessel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Greg Veum",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Rose Casper",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Gabriel Kub",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Robyn Spinka",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kelley Cruickshank",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Frances Marvin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Isabel Sauer",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Alberta Mueller",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jacquelyn Volkman",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Hugo Kuhlman",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Bertha Mohr",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lola Boehm",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lynn Lesch",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Rose Strosin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "John Heidenreich",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Emanuel Fay",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Joanne Mohr",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kim Sipes",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Hope Collins",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Edmund Hackett",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Marguerite Raynor",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Tami Hilpert",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Tonya Crist",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Dallas Flatley",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jan Durgan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Charlotte Lehner",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Salvatore Harris",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Seth Emard",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Nettie Hoeger",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Chester Osinski",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Frederick Torphy",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Everett Huel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Karen Osinski",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Alfonso Littel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Hilda Monahan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Devin Robel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Eva Kreiger",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Antonio Kertzmann",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Frank Beier",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lois Halvorson",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Darin Hickle",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Shelia Stracke",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jackie Hansen",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Glenn Schmidt",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Luke Considine",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Roderick Lakin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Ed Langosh",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Stuart Bogan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Eva Cremin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jo Swaniawski",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Blanca Effertz",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Joan Jacobs",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Luz Stehr",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Brittany Corwin",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Erin Price",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Jeanne Ritchie",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Timmy Wilkinson",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Lorene Robel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Garry Ferry",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Alex Rohan",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Ricardo Flatley",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Kelly Rosenbaum",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Josephine Brekke",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Darrell Dickens",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Stewart Thiel",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        },
                        new
                        {
                            Username = "Boyd Roob",
                            Balance = 0m,
                            BalanceIn = 0m,
                            BalanceOut = 0m,
                            Creater = "george",
                            DoubleBunosActive = "Active",
                            Ip = "l",
                            LastLogin = new DateTime(2020, 12, 20, 19, 14, 57, 0, DateTimeKind.Unspecified),
                            Level = 0.0,
                            LoginTimes = 0,
                            Password = "159753Abo",
                            PercantageOfLuck = 70,
                            Status = "off",
                            UserType = "Player"
                        });
                });

            modelBuilder.Entity("Data_Access.Models.ChargeHistory", b =>
                {
                    b.HasOne("Data_Access.Models.User", "User")
                        .WithMany("ChargeHistories")
                        .HasForeignKey("Creater")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Access.Models.GameHistory", b =>
                {
                    b.HasOne("Data_Access.Models.User", "User")
                        .WithMany("GameHistories")
                        .HasForeignKey("Creater")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Access.Models.LoginHistory", b =>
                {
                    b.HasOne("Data_Access.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("Creater")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Access.Models.User", b =>
                {
                    b.Navigation("ChargeHistories");

                    b.Navigation("GameHistories");

                    b.Navigation("LoginHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
